// AUTO-GENERATED from KPOCHA TOUCH — UNIVERSAL PROFESSI.txt
// Do not edit by hand; re-run scripts/generateUniversalList.js instead.

export const UNIVERSAL_PROFESSIONS = [
  { id: 'beauty_personal_care__barbers', name: 'Barbers', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__hair_stylists', name: 'Hair Stylists', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__makeup_artists', name: 'Makeup Artists', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__nail_technicians', name: 'Nail Technicians', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__skincare_specialists', name: 'Skincare Specialists', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__massage_therapists', name: 'Massage Therapists', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__spa_wellness_experts', name: 'Spa & Wellness Experts', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__beard_grooming_specialists', name: 'Beard Grooming Specialists', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__fashion_stylists', name: 'Fashion Stylists', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__barbing_grooming', name: 'Barbing & Grooming', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__men_s_haircut', name: 'Men’s Haircut', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__women_s_low_cut', name: 'Women’s Low Cut', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__children_haircut', name: 'Children Haircut', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__beard_trim', name: 'Beard Trim', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__beard_styling', name: 'Beard Styling', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__shaving', name: 'Shaving', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__home_service_haircut', name: 'Home Service Haircut', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__hair_styling', name: 'Hair & Styling', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__braiding', name: 'Braiding', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__weaving', name: 'Weaving', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__wig_installation', name: 'Wig Installation', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__wig_revamp', name: 'Wig Revamp', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__hair_coloring', name: 'Hair Coloring', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__hair_treatment', name: 'Hair Treatment', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__dreadlocks_installation', name: 'Dreadlocks Installation', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__dread_maintenance', name: 'Dread Maintenance', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__makeup_beauty', name: 'Makeup & Beauty', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__full_glam_makeup', name: 'Full Glam Makeup', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__bridal_makeup', name: 'Bridal Makeup', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__casual_makeup', name: 'Casual Makeup', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__photoshoot_makeup', name: 'Photoshoot Makeup', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__gele_tying', name: 'Gele Tying', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__nails_skincare', name: 'Nails & Skincare', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__manicure', name: 'Manicure', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__pedicure', name: 'Pedicure', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__acrylic_nails', name: 'Acrylic Nails', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__gel_nails', name: 'Gel Nails', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__facials', name: 'Facials', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__body_massage', name: 'Body Massage', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__body_scrub', name: 'Body Scrub', category: 'Beauty & Personal Care' },
  { id: 'beauty_personal_care__waxing', name: 'Waxing', category: 'Beauty & Personal Care' },
  { id: 'health_medical__nurses', name: 'Nurses', category: 'Health & Medical' },
  { id: 'health_medical__midwives', name: 'Midwives', category: 'Health & Medical' },
  { id: 'health_medical__lab_scientists', name: 'Lab Scientists', category: 'Health & Medical' },
  { id: 'health_medical__physiotherapists', name: 'Physiotherapists', category: 'Health & Medical' },
  { id: 'health_medical__pharmacists', name: 'Pharmacists', category: 'Health & Medical' },
  { id: 'health_medical__radiographers', name: 'Radiographers', category: 'Health & Medical' },
  { id: 'health_medical__opticians', name: 'Opticians', category: 'Health & Medical' },
  { id: 'health_medical__nutritionists', name: 'Nutritionists', category: 'Health & Medical' },
  { id: 'health_medical__herbal_alternative_medicine_practitioners', name: 'Herbal/Alternative Medicine Practitioners', category: 'Health & Medical' },
  { id: 'health_medical__home_nursing_care', name: 'Home Nursing Care', category: 'Health & Medical' },
  { id: 'health_medical__injection_service', name: 'Injection Service', category: 'Health & Medical' },
  { id: 'health_medical__iv_drip_administration', name: 'IV Drip Administration', category: 'Health & Medical' },
  { id: 'health_medical__wound_dressing', name: 'Wound Dressing', category: 'Health & Medical' },
  { id: 'health_medical__physiotherapy_session', name: 'Physiotherapy Session', category: 'Health & Medical' },
  { id: 'health_medical__blood_pressure_check', name: 'Blood Pressure Check', category: 'Health & Medical' },
  { id: 'health_medical__blood_sugar_test', name: 'Blood Sugar Test', category: 'Health & Medical' },
  { id: 'health_medical__prenatal_care', name: 'Prenatal Care', category: 'Health & Medical' },
  { id: 'health_medical__postnatal_care', name: 'Postnatal Care', category: 'Health & Medical' },
  { id: 'health_medical__lab_sample_collection', name: 'Lab Sample Collection', category: 'Health & Medical' },
  { id: 'health_medical__herbal_consultation', name: 'Herbal Consultation', category: 'Health & Medical' },
  { id: 'health_medical__nutrition_coaching', name: 'Nutrition Coaching', category: 'Health & Medical' },
  { id: 'home_services__electricians', name: 'Electricians', category: 'Home Services' },
  { id: 'home_services__plumbers', name: 'Plumbers', category: 'Home Services' },
  { id: 'home_services__carpenters', name: 'Carpenters', category: 'Home Services' },
  { id: 'home_services__painters', name: 'Painters', category: 'Home Services' },
  { id: 'home_services__welders', name: 'Welders', category: 'Home Services' },
  { id: 'home_services__tilers', name: 'Tilers', category: 'Home Services' },
  { id: 'home_services__ac_fridge_repair_technicians', name: 'AC/Fridge Repair Technicians', category: 'Home Services' },
  { id: 'home_services__generator_repair_technicians', name: 'Generator Repair Technicians', category: 'Home Services' },
  { id: 'home_services__solar_technicians', name: 'Solar Technicians', category: 'Home Services' },
  { id: 'home_services__house_cleaners', name: 'House Cleaners', category: 'Home Services' },
  { id: 'home_services__pest_control_experts', name: 'Pest Control Experts', category: 'Home Services' },
  { id: 'home_services__electrical_repairs', name: 'Electrical Repairs', category: 'Home Services' },
  { id: 'home_services__wiring_installation', name: 'Wiring Installation', category: 'Home Services' },
  { id: 'home_services__plumbing_repairs', name: 'Plumbing Repairs', category: 'Home Services' },
  { id: 'home_services__borehole_repair', name: 'Borehole Repair', category: 'Home Services' },
  { id: 'home_services__carpentry_work', name: 'Carpentry Work', category: 'Home Services' },
  { id: 'home_services__furniture_repair', name: 'Furniture Repair', category: 'Home Services' },
  { id: 'home_services__painting_service', name: 'Painting Service', category: 'Home Services' },
  { id: 'home_services__pop_installation', name: 'POP Installation', category: 'Home Services' },
  { id: 'home_services__welding_fabrication', name: 'Welding/Fabrication', category: 'Home Services' },
  { id: 'home_services__tiling', name: 'Tiling', category: 'Home Services' },
  { id: 'home_services__ac_fridge_repair', name: 'AC/Fridge Repair', category: 'Home Services' },
  { id: 'home_services__generator_repair', name: 'Generator Repair', category: 'Home Services' },
  { id: 'home_services__solar_installation', name: 'Solar Installation', category: 'Home Services' },
  { id: 'home_services__house_cleaning', name: 'House Cleaning', category: 'Home Services' },
  { id: 'home_services__fumigation_pest_control', name: 'Fumigation & Pest Control', category: 'Home Services' },
  { id: 'automotive__mechanics', name: 'Mechanics', category: 'Automotive' },
  { id: 'automotive__auto_electricians', name: 'Auto Electricians', category: 'Automotive' },
  { id: 'automotive__panel_beaters', name: 'Panel Beaters', category: 'Automotive' },
  { id: 'automotive__spray_painters', name: 'Spray Painters', category: 'Automotive' },
  { id: 'automotive__car_wash_detailing', name: 'Car Wash/Detailing', category: 'Automotive' },
  { id: 'automotive__tyre_wheel_alignment', name: 'Tyre & Wheel Alignment', category: 'Automotive' },
  { id: 'automotive__vehicle_inspection_experts', name: 'Vehicle Inspection Experts', category: 'Automotive' },
  { id: 'automotive__vehicle_diagnosis', name: 'Vehicle Diagnosis', category: 'Automotive' },
  { id: 'automotive__engine_repair', name: 'Engine Repair', category: 'Automotive' },
  { id: 'automotive__gearbox_repair', name: 'Gearbox Repair', category: 'Automotive' },
  { id: 'automotive__brake_service', name: 'Brake Service', category: 'Automotive' },
  { id: 'automotive__oil_change', name: 'Oil Change', category: 'Automotive' },
  { id: 'automotive__car_ac_repair', name: 'Car AC Repair', category: 'Automotive' },
  { id: 'automotive__panel_beating', name: 'Panel Beating', category: 'Automotive' },
  { id: 'automotive__spray_painting', name: 'Spray Painting', category: 'Automotive' },
  { id: 'automotive__car_wash', name: 'Car Wash', category: 'Automotive' },
  { id: 'automotive__wheel_balancing', name: 'Wheel Balancing', category: 'Automotive' },
  { id: 'automotive__tyre_change', name: 'Tyre Change', category: 'Automotive' },
  { id: 'automotive__car_detailing', name: 'Car Detailing', category: 'Automotive' },
  { id: 'tech_digital_services__web_developers', name: 'Web Developers', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__mobile_app_developers', name: 'Mobile App Developers', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__ui_ux_designers', name: 'UI/UX Designers', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__graphics_designers', name: 'Graphics Designers', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__photographers', name: 'Photographers', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__videographers', name: 'Videographers', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__social_media_managers', name: 'Social Media Managers', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__digital_marketers', name: 'Digital Marketers', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__cybersecurity_experts', name: 'Cybersecurity Experts', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__data_analysts', name: 'Data Analysts', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__computer_repair_technicians', name: 'Computer Repair Technicians', category: 'Tech & Digital Services' },
  { id: 'tech_digital_services__cctv_smart_home_installers', name: 'CCTV/Smart Home Installers', category: 'Tech & Digital Services' },
  { id: 'events_entertainment__event_planners', name: 'Event Planners', category: 'Events & Entertainment' },
  { id: 'events_entertainment__mcs_comedians', name: 'MCs / Comedians', category: 'Events & Entertainment' },
  { id: 'events_entertainment__djs', name: 'DJs', category: 'Events & Entertainment' },
  { id: 'events_entertainment__live_bands_musicians', name: 'Live Bands / Musicians', category: 'Events & Entertainment' },
  { id: 'events_entertainment__decorators', name: 'Decorators', category: 'Events & Entertainment' },
  { id: 'events_entertainment__caterers', name: 'Caterers', category: 'Events & Entertainment' },
  { id: 'events_entertainment__ushers', name: 'Ushers', category: 'Events & Entertainment' },
  { id: 'events_entertainment__event_rentals_chairs_tents_sound', name: 'Event Rentals (chairs, tents, sound)', category: 'Events & Entertainment' },
  { id: 'events_entertainment__photobooth_operators', name: 'Photobooth Operators', category: 'Events & Entertainment' },
  { id: 'events_entertainment__event_planning', name: 'Event Planning', category: 'Events & Entertainment' },
  { id: 'events_entertainment__mc_service', name: 'MC Service', category: 'Events & Entertainment' },
  { id: 'events_entertainment__dj_service', name: 'DJ Service', category: 'Events & Entertainment' },
  { id: 'events_entertainment__live_band_performance', name: 'Live Band Performance', category: 'Events & Entertainment' },
  { id: 'events_entertainment__decoration', name: 'Decoration', category: 'Events & Entertainment' },
  { id: 'events_entertainment__catering', name: 'Catering', category: 'Events & Entertainment' },
  { id: 'events_entertainment__small_chops_supply', name: 'Small Chops Supply', category: 'Events & Entertainment' },
  { id: 'events_entertainment__ushers', name: 'Ushers', category: 'Events & Entertainment' },
  { id: 'events_entertainment__chair_table_rentals', name: 'Chair/Table Rentals', category: 'Events & Entertainment' },
  { id: 'events_entertainment__canopy_rentals', name: 'Canopy Rentals', category: 'Events & Entertainment' },
  { id: 'events_entertainment__sound_system_rentals', name: 'Sound System Rentals', category: 'Events & Entertainment' },
  { id: 'events_entertainment__photography', name: 'Photography', category: 'Events & Entertainment' },
  { id: 'events_entertainment__videography', name: 'Videography', category: 'Events & Entertainment' },
  { id: 'teaching_education__private_tutors', name: 'Private Tutors', category: 'Teaching & Education' },
  { id: 'teaching_education__language_teachers', name: 'Language Teachers', category: 'Teaching & Education' },
  { id: 'teaching_education__skill_trainers_tech_makeup_tailoring_etc', name: 'Skill Trainers (Tech, Makeup, Tailoring, etc.)', category: 'Teaching & Education' },
  { id: 'teaching_education__music_instructors', name: 'Music Instructors', category: 'Teaching & Education' },
  { id: 'teaching_education__dance_instructors', name: 'Dance Instructors', category: 'Teaching & Education' },
  { id: 'teaching_education__home_tutoring', name: 'Home Tutoring', category: 'Teaching & Education' },
  { id: 'teaching_education__waec_neco_coaching', name: 'WAEC/NECO Coaching', category: 'Teaching & Education' },
  { id: 'teaching_education__jamb_coaching', name: 'JAMB Coaching', category: 'Teaching & Education' },
  { id: 'teaching_education__language_lessons', name: 'Language Lessons', category: 'Teaching & Education' },
  { id: 'teaching_education__music_lessons', name: 'Music Lessons', category: 'Teaching & Education' },
  { id: 'teaching_education__dance_lessons', name: 'Dance Lessons', category: 'Teaching & Education' },
  { id: 'teaching_education__skill_training_tech_makeup_tailoring_etc', name: 'Skill Training (tech, makeup, tailoring, etc.)', category: 'Teaching & Education' },
  { id: 'business_professional_services__accountants', name: 'Accountants', category: 'Business & Professional Services' },
  { id: 'business_professional_services__business_consultants', name: 'Business Consultants', category: 'Business & Professional Services' },
  { id: 'business_professional_services__legal_consultants_paralegals', name: 'Legal Consultants / Paralegals', category: 'Business & Professional Services' },
  { id: 'business_professional_services__real_estate_agents', name: 'Real Estate Agents', category: 'Business & Professional Services' },
  { id: 'business_professional_services__property_managers', name: 'Property Managers', category: 'Business & Professional Services' },
  { id: 'business_professional_services__insurance_advisors', name: 'Insurance Advisors', category: 'Business & Professional Services' },
  { id: 'business_professional_services__loan_agents', name: 'Loan Agents', category: 'Business & Professional Services' },
  { id: 'business_professional_services__writers_editors', name: 'Writers / Editors', category: 'Business & Professional Services' },
  { id: 'business_professional_services__translators', name: 'Translators', category: 'Business & Professional Services' },
  { id: 'business_professional_services__accounting', name: 'Accounting', category: 'Business & Professional Services' },
  { id: 'business_professional_services__tax_filing', name: 'Tax Filing', category: 'Business & Professional Services' },
  { id: 'business_professional_services__business_registration', name: 'Business Registration', category: 'Business & Professional Services' },
  { id: 'business_professional_services__business_consultancy', name: 'Business Consultancy', category: 'Business & Professional Services' },
  { id: 'business_professional_services__legal_advisory', name: 'Legal Advisory', category: 'Business & Professional Services' },
  { id: 'business_professional_services__real_estate_buying_selling', name: 'Real Estate Buying/Selling', category: 'Business & Professional Services' },
  { id: 'business_professional_services__property_management', name: 'Property Management', category: 'Business & Professional Services' },
  { id: 'business_professional_services__copywriting', name: 'Copywriting', category: 'Business & Professional Services' },
  { id: 'business_professional_services__editing_proofreading', name: 'Editing & Proofreading', category: 'Business & Professional Services' },
  { id: 'business_professional_services__document_drafting', name: 'Document Drafting', category: 'Business & Professional Services' },
  { id: 'business_professional_services__translation', name: 'Translation', category: 'Business & Professional Services' },
  { id: 'business_professional_services__insurance_advisory', name: 'Insurance Advisory', category: 'Business & Professional Services' },
  { id: 'fashion_handcraft__tailors', name: 'Tailors', category: 'Fashion & Handcraft' },
  { id: 'fashion_handcraft__fashion_designers', name: 'Fashion Designers', category: 'Fashion & Handcraft' },
  { id: 'fashion_handcraft__bag_makers', name: 'Bag Makers', category: 'Fashion & Handcraft' },
  { id: 'fashion_handcraft__shoe_makers', name: 'Shoe Makers', category: 'Fashion & Handcraft' },
  { id: 'fashion_handcraft__leather_workers', name: 'Leather Workers', category: 'Fashion & Handcraft' },
  { id: 'fashion_handcraft__jewelry_designers', name: 'Jewelry Designers', category: 'Fashion & Handcraft' },
  { id: 'fashion_handcraft__embroidery_experts', name: 'Embroidery Experts', category: 'Fashion & Handcraft' },
  { id: 'fashion_handcraft__bead_makers', name: 'Bead Makers', category: 'Fashion & Handcraft' },
  { id: 'food_kitchen_services__chefs', name: 'Chefs', category: 'Food & Kitchen Services' },
  { id: 'food_kitchen_services__bakers', name: 'Bakers', category: 'Food & Kitchen Services' },
  { id: 'food_kitchen_services__pastry_artists', name: 'Pastry Artists', category: 'Food & Kitchen Services' },
  { id: 'food_kitchen_services__home_meal_providers', name: 'Home Meal Providers', category: 'Food & Kitchen Services' },
  { id: 'food_kitchen_services__small_chops_vendors', name: 'Small Chops Vendors', category: 'Food & Kitchen Services' },
  { id: 'food_kitchen_services__mixologists', name: 'Mixologists', category: 'Food & Kitchen Services' },
  { id: 'food_kitchen_services__beverage_suppliers', name: 'Beverage Suppliers', category: 'Food & Kitchen Services' },
  { id: 'fitness_sports__personal_trainers', name: 'Personal Trainers', category: 'Fitness & Sports' },
  { id: 'fitness_sports__yoga_instructors', name: 'Yoga Instructors', category: 'Fitness & Sports' },
  { id: 'fitness_sports__fitness_coaches', name: 'Fitness Coaches', category: 'Fitness & Sports' },
  { id: 'fitness_sports__dance_fitness_experts', name: 'Dance Fitness Experts', category: 'Fitness & Sports' },
  { id: 'fitness_sports__sports_therapists', name: 'Sports Therapists', category: 'Fitness & Sports' },
  { id: 'fitness_sports__personal_training', name: 'Personal Training', category: 'Fitness & Sports' },
  { id: 'fitness_sports__weight_loss_coaching', name: 'Weight Loss Coaching', category: 'Fitness & Sports' },
  { id: 'fitness_sports__yoga_sessions', name: 'Yoga Sessions', category: 'Fitness & Sports' },
  { id: 'fitness_sports__aerobics_instruction', name: 'Aerobics Instruction', category: 'Fitness & Sports' },
  { id: 'fitness_sports__sports_therapy', name: 'Sports Therapy', category: 'Fitness & Sports' },
  { id: 'fitness_sports__dance_fitness', name: 'Dance Fitness', category: 'Fitness & Sports' },
  { id: 'construction_engineering__civil_engineers', name: 'Civil Engineers', category: 'Construction & Engineering' },
  { id: 'construction_engineering__building_contractors', name: 'Building Contractors', category: 'Construction & Engineering' },
  { id: 'construction_engineering__structural_engineers', name: 'Structural Engineers', category: 'Construction & Engineering' },
  { id: 'construction_engineering__surveyors', name: 'Surveyors', category: 'Construction & Engineering' },
  { id: 'construction_engineering__architects', name: 'Architects', category: 'Construction & Engineering' },
  { id: 'construction_engineering__site_supervisors', name: 'Site Supervisors', category: 'Construction & Engineering' },
  { id: 'construction_engineering__heavy_equipment_operators', name: 'Heavy Equipment Operators', category: 'Construction & Engineering' },
  { id: 'construction_engineering__building_construction', name: 'Building Construction', category: 'Construction & Engineering' },
  { id: 'construction_engineering__site_supervision', name: 'Site Supervision', category: 'Construction & Engineering' },
  { id: 'construction_engineering__architectural_drawing', name: 'Architectural Drawing', category: 'Construction & Engineering' },
  { id: 'construction_engineering__surveying', name: 'Surveying', category: 'Construction & Engineering' },
  { id: 'construction_engineering__structural_design', name: 'Structural Design', category: 'Construction & Engineering' },
  { id: 'construction_engineering__interior_design', name: 'Interior Design', category: 'Construction & Engineering' },
  { id: 'construction_engineering__pop_partitioning', name: 'POP & Partitioning', category: 'Construction & Engineering' },
  { id: 'construction_engineering__borehole_drilling', name: 'Borehole Drilling', category: 'Construction & Engineering' },
  { id: 'construction_engineering__interlocking', name: 'Interlocking', category: 'Construction & Engineering' },
  { id: 'construction_engineering__roofing', name: 'Roofing', category: 'Construction & Engineering' },
  { id: 'logistics_mobility__dispatch_riders', name: 'Dispatch Riders', category: 'Logistics & Mobility' },
  { id: 'logistics_mobility__taxi_ride_hailing_drivers', name: 'Taxi/Ride-Hailing Drivers', category: 'Logistics & Mobility' },
  { id: 'logistics_mobility__truck_drivers', name: 'Truck Drivers', category: 'Logistics & Mobility' },
  { id: 'logistics_mobility__movers_packers', name: 'Movers & Packers', category: 'Logistics & Mobility' },
  { id: 'logistics_mobility__delivery_services', name: 'Delivery Services', category: 'Logistics & Mobility' },
  { id: 'childcare_family_services__nannies', name: 'Nannies', category: 'Childcare & Family Services' },
  { id: 'childcare_family_services__babysitters', name: 'Babysitters', category: 'Childcare & Family Services' },
  { id: 'childcare_family_services__caregivers', name: 'Caregivers', category: 'Childcare & Family Services' },
  { id: 'childcare_family_services__elderly_care_assistants', name: 'Elderly Care Assistants', category: 'Childcare & Family Services' },
  { id: 'childcare_family_services__special_needs_aides', name: 'Special Needs Aides', category: 'Childcare & Family Services' },
  { id: 'agriculture_environmental__farmers', name: 'Farmers', category: 'Agriculture & Environmental' },
  { id: 'agriculture_environmental__agro_consultants', name: 'Agro Consultants', category: 'Agriculture & Environmental' },
  { id: 'agriculture_environmental__landscapers', name: 'Landscapers', category: 'Agriculture & Environmental' },
  { id: 'agriculture_environmental__gardeners', name: 'Gardeners', category: 'Agriculture & Environmental' },
  { id: 'agriculture_environmental__waste_management_experts', name: 'Waste Management Experts', category: 'Agriculture & Environmental' },
  { id: 'agriculture_environmental__water_treatment_specialists', name: 'Water Treatment Specialists', category: 'Agriculture & Environmental' },
  { id: 'security_services__security_guards', name: 'Security Guards', category: 'Security Services' },
  { id: 'security_services__bouncers', name: 'Bouncers', category: 'Security Services' },
  { id: 'security_services__bodyguards', name: 'Bodyguards', category: 'Security Services' },
  { id: 'security_services__cctv_monitoring_experts', name: 'CCTV Monitoring Experts', category: 'Security Services' },
  { id: 'security_services__private_investigators', name: 'Private Investigators', category: 'Security Services' },
  { id: 'security_services__security_guard', name: 'Security Guard', category: 'Security Services' },
  { id: 'security_services__bouncer_service', name: 'Bouncer Service', category: 'Security Services' },
  { id: 'security_services__bodyguard_service', name: 'Bodyguard Service', category: 'Security Services' },
  { id: 'security_services__cctv_monitoring', name: 'CCTV Monitoring', category: 'Security Services' },
  { id: 'security_services__private_investigation', name: 'Private Investigation', category: 'Security Services' },
  { id: 'art_media_creativity__painters_artists', name: 'Painters (artists)', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__sculptors', name: 'Sculptors', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__illustrators', name: 'Illustrators', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__writers', name: 'Writers', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__voice_over_artists', name: 'Voice-over Artists', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__actors_actresses', name: 'Actors / Actresses', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__cinematographers', name: 'Cinematographers', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__animators', name: 'Animators', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__painting_canvas_wall', name: 'Painting (Canvas/Wall)', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__mural_design', name: 'Mural Design', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__illustration', name: 'Illustration', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__voice_over_recording', name: 'Voice-Over Recording', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__script_writing', name: 'Script Writing', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__acting_service', name: 'Acting Service', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__animation', name: 'Animation', category: 'Art, Media & Creativity' },
  { id: 'art_media_creativity__cinematography', name: 'Cinematography', category: 'Art, Media & Creativity' },
  { id: 'miscellaneous_other_services__for_rare_or_emerging_categories', name: '(For rare or emerging categories)', category: 'Miscellaneous / Other Services' },
  { id: 'miscellaneous_other_services__errand_runners', name: 'Errand Runners', category: 'Miscellaneous / Other Services' },
  { id: 'miscellaneous_other_services__personal_assistants', name: 'Personal Assistants', category: 'Miscellaneous / Other Services' },
  { id: 'miscellaneous_other_services__repair_technicians_general', name: 'Repair Technicians (general)', category: 'Miscellaneous / Other Services' },
  { id: 'miscellaneous_other_services__custom_service_providers', name: 'Custom Service Providers', category: 'Miscellaneous / Other Services' },
  { id: 'miscellaneous_other_services__kpocha_touch_master_service_list_by_category', name: '✅ KPOCHA TOUCH — MASTER SERVICE LIST (BY CATEGORY)', category: 'Miscellaneous / Other Services' },
  { id: 'tech_digital__web_development', name: 'Web Development', category: 'Tech & Digital' },
  { id: 'tech_digital__mobile_app_development', name: 'Mobile App Development', category: 'Tech & Digital' },
  { id: 'tech_digital__ui_ux_design', name: 'UI/UX Design', category: 'Tech & Digital' },
  { id: 'tech_digital__logo_design', name: 'Logo Design', category: 'Tech & Digital' },
  { id: 'tech_digital__graphics_design', name: 'Graphics Design', category: 'Tech & Digital' },
  { id: 'tech_digital__cctv_installation', name: 'CCTV Installation', category: 'Tech & Digital' },
  { id: 'tech_digital__inverter_solar_setup', name: 'Inverter/Solar Setup', category: 'Tech & Digital' },
  { id: 'tech_digital__computer_repair', name: 'Computer Repair', category: 'Tech & Digital' },
  { id: 'tech_digital__phone_repair', name: 'Phone Repair', category: 'Tech & Digital' },
  { id: 'tech_digital__data_analysis', name: 'Data Analysis', category: 'Tech & Digital' },
  { id: 'tech_digital__cybersecurity_audit', name: 'Cybersecurity Audit', category: 'Tech & Digital' },
  { id: 'tech_digital__social_media_management', name: 'Social Media Management', category: 'Tech & Digital' },
  { id: 'tech_digital__video_editing', name: 'Video Editing', category: 'Tech & Digital' },
  { id: 'tech_digital__photography_session', name: 'Photography Session', category: 'Tech & Digital' },
  { id: 'fashion_tailoring__native_wear_sewing', name: 'Native Wear Sewing', category: 'Fashion & Tailoring' },
  { id: 'fashion_tailoring__english_wear_sewing', name: 'English Wear Sewing', category: 'Fashion & Tailoring' },
  { id: 'fashion_tailoring__dress_making', name: 'Dress Making', category: 'Fashion & Tailoring' },
  { id: 'fashion_tailoring__suit_tailoring', name: 'Suit Tailoring', category: 'Fashion & Tailoring' },
  { id: 'fashion_tailoring__clothing_adjustments', name: 'Clothing Adjustments', category: 'Fashion & Tailoring' },
  { id: 'fashion_tailoring__wig_making', name: 'Wig Making', category: 'Fashion & Tailoring' },
  { id: 'fashion_tailoring__wig_styling', name: 'Wig Styling', category: 'Fashion & Tailoring' },
  { id: 'fashion_tailoring__custom_handbags', name: 'Custom Handbags', category: 'Fashion & Tailoring' },
  { id: 'fashion_tailoring__shoe_making_repair', name: 'Shoe Making/Repair', category: 'Fashion & Tailoring' },
  { id: 'food_catering__private_chef_service', name: 'Private Chef Service', category: 'Food & Catering' },
  { id: 'food_catering__event_catering', name: 'Event Catering', category: 'Food & Catering' },
  { id: 'food_catering__small_chops_delivery', name: 'Small Chops Delivery', category: 'Food & Catering' },
  { id: 'food_catering__pastry_baking', name: 'Pastry Baking', category: 'Food & Catering' },
  { id: 'food_catering__cake_baking', name: 'Cake Baking', category: 'Food & Catering' },
  { id: 'food_catering__cocktail_mixing', name: 'Cocktail Mixing', category: 'Food & Catering' },
  { id: 'food_catering__food_tray_delivery', name: 'Food Tray Delivery', category: 'Food & Catering' },
  { id: 'food_catering__meal_prep_service', name: 'Meal Prep Service', category: 'Food & Catering' },
  { id: 'logistics_delivery__dispatch_delivery', name: 'Dispatch Delivery', category: 'Logistics & Delivery' },
  { id: 'logistics_delivery__taxi_ride_service', name: 'Taxi/Ride Service', category: 'Logistics & Delivery' },
  { id: 'logistics_delivery__truck_van_booking', name: 'Truck/Van Booking', category: 'Logistics & Delivery' },
  { id: 'logistics_delivery__house_moving', name: 'House Moving', category: 'Logistics & Delivery' },
  { id: 'logistics_delivery__package_pickup', name: 'Package Pickup', category: 'Logistics & Delivery' },
  { id: 'logistics_delivery__errand_running', name: 'Errand Running', category: 'Logistics & Delivery' },
  { id: 'childcare_family__babysitting', name: 'Babysitting', category: 'Childcare & Family' },
  { id: 'childcare_family__nanny_service', name: 'Nanny Service', category: 'Childcare & Family' },
  { id: 'childcare_family__elderly_care', name: 'Elderly Care', category: 'Childcare & Family' },
  { id: 'childcare_family__special_needs_support', name: 'Special Needs Support', category: 'Childcare & Family' },
  { id: 'childcare_family__home_help_service', name: 'Home Help Service', category: 'Childcare & Family' },
  { id: 'agriculture_environment__landscaping', name: 'Landscaping', category: 'Agriculture & Environment' },
  { id: 'agriculture_environment__lawn_mowing', name: 'Lawn Mowing', category: 'Agriculture & Environment' },
  { id: 'agriculture_environment__garden_setup', name: 'Garden Setup', category: 'Agriculture & Environment' },
  { id: 'agriculture_environment__agro_consultancy', name: 'Agro Consultancy', category: 'Agriculture & Environment' },
  { id: 'agriculture_environment__farm_management', name: 'Farm Management', category: 'Agriculture & Environment' },
  { id: 'agriculture_environment__water_treatment_services', name: 'Water Treatment Services', category: 'Agriculture & Environment' },
  { id: 'miscellaneous_services__errand_running', name: 'Errand Running', category: 'Miscellaneous Services' },
  { id: 'miscellaneous_services__personal_assistant', name: 'Personal Assistant', category: 'Miscellaneous Services' },
  { id: 'miscellaneous_services__home_organization', name: 'Home Organization', category: 'Miscellaneous Services' },
  { id: 'miscellaneous_services__laundry_ironing', name: 'Laundry/Ironing', category: 'Miscellaneous Services' },
  { id: 'miscellaneous_services__repairs_general', name: 'Repairs (general)', category: 'Miscellaneous Services' },
];
